### ISSUE TITLE
Got "[Error: Secure random number generation is not supported by this browser. Use Chrome, Firefox or Internet Explorer 11]"

### ISSUE THREAD

**Issue by arantespp** [asgardeo/asgardeo-react-native-oidc-sdk#16]
## Description

I got the error `[Error: Secure random number generation is not supported by this browser. Use Chrome, Firefox or Internet Explorer 11]` when calling the method `getAuthorizationURL` [here](https://github.com/asgardeo/asgardeo-react-native-oidc-sdk/blob/304cb94efd7dc747592729414b58109c9e81f1dd/sample/Screen/LoginScreen.js#L91).

I suspect that the error comes from the method `getCodeVerifier` [here](https://github.com/asgardeo/asgardeo-auth-js-sdk/blob/master/lib/src/utils/crypto-utils.ts) because it uses the package `randombytes`. There is also an issue with the same error https://github.com/crypto-browserify/randombytes/issues/6

**Comment by ThaminduDilshan** [comment]
Hi @arantespp 

Would you be able to share below information with us?
- `@asgardeo/auth-js` version being used
- OS being used: Android or iOS
- Did this error occur in Asgardeo react native sample application?
- Did you run application in an emulator or actual device?

**Comment by ThaminduDilshan** [comment]
> ## Details
> * _`@asgardeo/auth-js` version being used_ I'm not using any `@asgardeo/auth-js` package (comments below).
> * _OS being used?_ Android
> * _Did this error occur in Asgardeo react-native sample application?_ Yes
> * _Did you run application in an emulator or actual device?_ Emulator
> 
> ## Status
> **The error was gone.**
> 
> The problem was the `utils/crypto-utils.ts` that I was using before from `@asgardeo/auth-js`. To fix this problem, I copied the whole `src` folder of both `@asgardeo/react-native-oidc-sdk` and `@asgardeo/auth-js` and removed the `crypto-utils.ts` of the `auth-js`. This way the App worked.
> 
> I did this because we can't install `@asgardeo/auth-react-native`, it doesn't exist on NPM.

That way the issue was fixed because the error is due to a library/ module we are using in auth-js SDK (which is being internally used by react native oidc SDK) which is not native compatible. The functionality didn't get broke because current React native SDK is not using the crypto-utils in `auth-js` package. 

We are currently being investigating these SDK issues.

**Comment by arantespp** [comment]
@ThaminduDilshan, do you have plans to fix these errors and publish the React Native SDK on NPM?

**Comment by ThaminduDilshan** [comment]
@arantespp We are currently in the process of revamping the React native SDK. We will address these issues as well during that effort.

**Comment by arantespp** [comment]
@ThaminduDilshan I'm following the JavaScript library. This PR may be enough for us https://github.com/asgardeo/asgardeo-auth-js-sdk/pull/165

**Comment by ThaminduDilshan** [comment]
You might need to get this [fix](https://github.com/asgardeo/asgardeo-auth-js-sdk/pull/166) as well.
