### ISSUE TITLE
Get "AsgardeoAuthNetworkException: Requesting access token failed" error

### ISSUE THREAD

**Issue by arantespp** [asgardeo/asgardeo-react-native-oidc-sdk#17]
## Description

I'm getting the error `[AsgardeoAuthNetworkException: Requesting access token failed]` when I call `requestAccessTokenDetails` after sign in using `getAuthorizationURL`. The URL returned has the following format: `myapp://login?code=SOME_CODE&session_state=SOME_SESSION_STATE`, in which `SOME_CODE` is an UUID v4 and `SOME_SESSION_STATE` is an invalid jwt. 

What could I do to debug this error? Is there a way to check if the error comes from an invalid server configuration or if my App is not configured properly?

I'm using the same configuration that I explained here https://github.com/asgardeo/asgardeo-react-native-oidc-sdk/issues/16#issuecomment-981972558

**Comment by ThaminduDilshan** [comment]
Hi @arantespp 

This looks like due to a `id_token` validation failure we have already observed and currently investigating into. To confirm, could you try setting the `validateIDToken` to `false` as mentioned [here](https://github.com/asgardeo/asgardeo-auth-react-sdk/issues/68#issuecomment-970394026)

**Comment by arantespp** [comment]
Hello @ThaminduDilshan. Thank you for your response.

Even setting `validateIDToken` to `false`, the error persists. 

I'm also performing some tests with Postman, and I could retrieve the tokens if I send a requisition with these properties:

```js
// Header
{
  Authorization: Bearer base64(client_id:client_secret)
}

// Body
{
  grant_type: "authorization_code",
  code: CODE,
  redirect_uri: REDIRECT_URI,
  scope: "openid",
  code_verifier: CODE_VERIFIER
}
```

If I remove the header `Authorization`, I get the error `"error_description": "Unsupported Client Authentication Method!"` Inspecting the SDK, it doesn't add the `Authorization` on headers. 

Is there another way or another configuration that I need to do to be able to call `requestAccessTokenDetails`?

**Comment by ThaminduDilshan** [comment]
@arantespp Have you enabled `public client` in Asgardeo for your application? The default react native sample app is documented to configure as a public client. Enabling [public client](https://wso2.com/asgardeo/docs/references/app-settings/oidc-settings-for-app/#public-client) allows clients to authenticate to Asgardeo without the client secret. 

If you haven't enabled it, you can do it by login to the Asgardeo console and visiting the edit page of your registered application. In there under **Protocol** tab, mark the **Public client** checkbox.

If you are planning to use this as a **Confidential application**, you have to provide the `clientSecret` along with the configuration options ([available configurations](https://github.com/asgardeo/asgardeo-auth-js-sdk#authclientconfigt)). However, if the application is meant to be a public client as defined by [Section 2.1 of OAuth 2.0](https://datatracker.ietf.org/doc/html/rfc6749#section-2.1) then it is not recommended to treat the application as a confidential application.

**Comment by arantespp** [comment]
It worked @ThaminduDilshan! We didn't have enabled `public client` in our server configuration. Thank you so much for your support :heart:

**Comment by ThaminduDilshan** [comment]
Disabling id token validation is actually not a solution. We are currently investigating on this issue.
