### ISSUE TITLE
State Callback URL is not correctly used

### ISSUE THREAD

**Issue by miguelbwso2** [asgardeo/asgardeo-react-native-oidc-sdk#21]
When we use "enablePKCE:true" as part of the config in the sample application, the app is not responding after the authentication in Identity Server.

We found that in "asgardeo-react-native-oidc/lib/src/authenticate.tsx" the function "requestAccessTokenDetails" is invoking to the function "requestAccessToken" in "asgardeo/auth-js" using the following code:

        const sessionState = dataList[1].split("=")[1];
        const authState = await AuthClient.requestAccessToken(code, sessionState);

But, the callback returned from  IS has the following structure:

http://10.0.2.2:8081/?code=b7db2038-3e4b-33ca-a9a3-7430ba2efd7b&state=request_2&session_state=15fe1b7ffb23e6eee7b5b4bccaabd3265d4e34df6a70d55f1614462f3c7441ea.CRLSU9GPoU0Eyhkji7tb7Q

So, if we change to use the following code, the sample application works properly:

        const state = dataList[1].split("=")[1];
        const sessionState = dataList[2].split("=")[1];

        const authState = await AuthClient.requestAccessToken(code, sessionState, state);

**Comment by thivi** [comment]
Hi @miguelbwso2,
Thank you for bringing this up. I have sent a PR with the required changes.
